docker-compose.yml, microservices/template/service.js
Will need this simple update to get microservice register working
=> refactor error that escaped first push

backend/package.json, backend/typescript/controllers/helpers.ts, backend/typescript/controllers/relationship.controller.ts, backend/typescript/models/relationship.model.ts, backend/typescript/seeding/seed.script.ts, commons/RamAPI.ts, tests/typescript/relationship.controller.spec.ts, tests/typescript/seeding/basic.seed.ts
Installed Mongoose validator and mongoose id validator
Added error handling for mongoose errors in response object
=> Backend data validation pattern established for one of the methods.

backend/swagger/api-docs/ram-api-docs.yaml
Applied standard API definition to Party/ Relationship/ Identity/ RelationshipType/ Relationship Attribute Name.  Other entities are not yet done.
=> Updating api definition  as per LMcK/DLoone chat

backend/typescript/controllers/relationshipType.controller.ts, backend/typescript/models/identity.model.ts, backend/typescript/models/relationshipAttributeName.model.ts, backend/typescript/tests/identity.model.spec.ts
Also includes missing startDate for the relationshipType.controller payload serialization.
=> Added the starting point for Identity

backend/typescript/controllers/helpers.ts, backend/typescript/controllers/relationship.controller.ts, backend/typescript/controllers/relationshipAttributeName.controller.ts, backend/typescript/controllers/relationshipType.controller.ts
=> Revert "Improved fluency of controller apis"

backend/swagger/api-docs/ram-api-docs.yaml, backend/typescript/models/relationshipAttributeName.model.ts, backend/typescript/seeding/seed.ts, backend/typescript/tests/relationshipAttributeName.model.spec.ts, commons/RamAPI.ts
As per architecture discussions to address limitations of the data model.
=> Added classifier and category to relationship attribute name

backend/package.json, backend/typescript/controllers/authenticator.simulator.controller.ts, backend/typescript/controllers/forgeRock.simulator.middleware.ts, backend/typescript/controllers/headers.ts, backend/typescript/controllers/security.middleware.ts, backend/typescript/server.ts, backend/typescript/tests/identity.model.spec.ts, docs/RAM.postman_collection.json, docs/RAM_local.postman_environment.json
In dev mode, there is an authenticator end point which sets an X-RAM-Auth-Token cookie.
In dev mode, there is a Forge Rock Simulator middleware that decodes X-RAM-Auth-Token into an Identity Id Value.
In dev mode, there is a Security Middleware which looks up the Identity and sets names, shared secrets to `res.locals` for controllers to use.
In prod mode, there is a Security Middleware which copies X-RAM-* headers to `res.locals` for controllers to use.
=> Added Authenticator Simulator Controller, Forge Rock Simulator Middleware, Security Middleware, Headers

backend/typescript/controllers/relationship.controller.ts, frontend/typescript/commons/ram-ng-validators.ts, frontend/typescript/components/add-relationship/add-relationship.component.html, frontend/typescript/components/add-relationship/add-relationship.component.ts, frontend/typescript/components/commons/access-period/access-period.component.ts, frontend/typescript/components/commons/authorisation-type/authorisation-type.component.ts, frontend/typescript/components/commons/declaration/declaration.component.html, frontend/typescript/components/commons/declaration/declaration.component.ts, frontend/typescript/components/commons/representative-details/individual-representative-details/individual-representative-details.component.html, frontend/typescript/components/commons/representative-details/individual-representative-details/individual-representative-details.component.ts, frontend/typescript/components/commons/representative-details/organisation-representative-details/organisation-representative-details.component.ts, frontend/typescript/components/commons/representative-details/representative-details.component.html, frontend/typescript/components/commons/representative-details/representative-details.component.ts
Validation of user input
Capturing all new relationship information in local json variable
User can click authorised only if all fields are valid
=> Add relationship page with angular components all binded together

backend/typescript/controllers/forgeRock.simulator.middleware.ts, backend/typescript/controllers/helpers.ts, backend/typescript/controllers/identity.controller.ts, backend/typescript/controllers/party.controller.ts, backend/typescript/controllers/relationship.controller.ts, backend/typescript/controllers/relationshipAttributeName.controller.ts, backend/typescript/controllers/relationshipType.controller.ts, backend/typescript/controllers/security.middleware.ts, backend/typescript/models/base.ts, backend/typescript/models/identity.model.ts, backend/typescript/models/party.model.ts, backend/typescript/models/profile.model.ts, backend/typescript/models/relationship.model.ts, backend/typescript/models/relationshipAttributeName.model.ts, backend/typescript/models/sharedSecret.model.ts, backend/typescript/seeding/seed.ts, backend/typescript/server.ts, backend/typescript/tests/identity.model.spec.ts, backend/typescript/tests/relationship.model.spec.ts, backend/typescript/tests/relationshipAttribute.model.spec.ts, commons/RamAPI.ts, docs/RAM.postman_collection.json, ram
Postman updated with relationship/add, and get/reject invitation.
Some endpoints now require authentication.
Some cleanup.
=> Add relationship, authentication, reject pending invitation

frontend/typescript/components/accept-authorisation/accept-authorisation.component.html, frontend/typescript/components/accept-authorisation/accept-authorisation.component.ts
=> Added date formatting via pipes

commons/RamAPI.ts, frontend/typescript/components/add-relationship-complete/add-relationship-complete.component.html, frontend/typescript/components/add-relationship-complete/add-relationship-complete.component.ts, frontend/typescript/components/add-relationship/add-relationship.component.ts, frontend/typescript/components/relationships/relationships.component.html, frontend/typescript/components/relationships/relationships.component.ts, frontend/typescript/services/ram-identity.service.ts, frontend/typescript/services/ram-rest.service.ts
Identity resolver is connected to authorisation-complete and relationship page
linked back to relationship
=> identity resolver working

frontend/typescript/components/add-relationship/add-relationship.component.ts, frontend/typescript/components/relationships-table/relationships-table.component.html, frontend/typescript/components/relationships-table/relationships-table.component.ts, frontend/typescript/components/relationships/relationships.component.html, frontend/typescript/components/relationships/relationships.component.ts, frontend/typescript/services/ram-rest.service.ts
=> Humanized relationship type label; Fixed tslint issues; Fixed api function name

frontend/typescript/components/add-relationship-complete/add-relationship-complete.component.html, frontend/typescript/components/add-relationship-complete/add-relationship-complete.component.ts, frontend/typescript/components/add-relationship/add-relationship.component.ts, frontend/typescript/components/app/app.component.ts, frontend/typescript/components/commons/representative-details/representative-details.component.ts
fix bug with naming in auth complete page
=> 	fix bug with naming in auth complete page 

backend/typescript/seeding/seed.ts
=> Added ASSOCIATE relationship type and updated seeder to use it for Jen and Jen's Catering

backend/typescript/controllers/headers.ts, backend/typescript/controllers/security.middleware.ts, frontend/dev/index.html, ram
Headers are now copied over to locals as lowercase.
Added deps:clean target to 'ram' script to clean node_modules and typings
=> Use lower case headers in code base to make case insensitive

backend/swagger/api-docs/ram-api-docs.yaml, backend/typescript/controllers/relationship.controller.ts, backend/typescript/models/party.model.ts, backend/typescript/models/relationship.model.ts, backend/typescript/seeding/seed-bobsmith-identity.ts, backend/typescript/seeding/seed-cakerybakery-identity.ts, backend/typescript/seeding/seed-cakerybakery-relationships.ts, backend/typescript/seeding/seed-jennifermaxim-identity.ts, backend/typescript/seeding/seed-jenscatering-identity.ts, backend/typescript/seeding/seed-jenscatering-relationships.ts, backend/typescript/seeding/seed-jmfoodpackaging-identity.ts, backend/typescript/seeding/seed-jmfoodpackaging-relationships.ts, backend/typescript/seeding/seed.ts, backend/typescript/tests/relationship.model.spec.ts, commons/RamAPI.ts, commons/RamAPI2.ts, docs/RAM.postman_collection.json, frontend/scss/app.scss, frontend/typescript/components/relationships/relationships.component.html, frontend/typescript/components/relationships/relationships.component.ts, frontend/typescript/services/ram-rest.service.ts
https://www.youtube.com/watch?v=ffYOqgycYmo
=> Spike of new UI for List Relationships; Refactoring of data seeder

frontend/typescript/components/accept-authorisation/accept-authorisation.component.html, frontend/typescript/components/add-relationship-complete/add-relationship-complete.component.html, frontend/typescript/components/add-relationship/add-relationship.component.html, frontend/typescript/components/enter-invitation-code/enter-invitation-code.component.html, frontend/typescript/components/page-header/page-header.component.ts, frontend/typescript/components/relationships/relationships.component.html
=> Page header component now supports context switching

backend/typescript/models/relationship.model.ts, frontend/index.html, frontend/scss/app.scss, frontend/typescript/components/app/app.component.html, frontend/typescript/components/relationships-table/relationships-table.component.ts, frontend/typescript/components/relationships/relationships.component.html, frontend/typescript/components/relationships/relationships.component.ts
=> First draft of the new view relationships screen

.gitignore, backend/swagger/api-docs/ram-api-docs.yaml, ram
Working on the REST API.
Also, I've added a parameter to ram script.  The npm is now running local, if you want to make the npm calls global in during setup, you need to specify with --global.
This is ongoing work for CI.
=> Cleaning up some of Swagger doco for AP353

frontend/gulpfile.js, ram
Added serve:with-browser-sync
Removed no-browser-sync option, serve is now without browser sync
=> Removed build-app from serve browser sync
